### ISSUE TITLE
Optional pagination to be supported by helix for incorrectly documented endpoints on Twitch reference

### ISSUE THREAD

**Issue by jackmcguire1** [nicklaw5/helix#33]
It's come to my attention that Twitch has incorrectly documented their endpoints...
their newer endpoints do actually support pagination although the docs do not r
eally state the fact they do, as identified by community devs.

see [github issue(s) raised for the Twitch Helix API](https://github.com/twitchdev/issues/issues/19)

**Comment by nicklaw5** [comment]
Thanks for bringing this to our attention

**Comment by jackmcguire1** [comment]
https://github.com/nicklaw5/helix/pull/112
