### ISSUE TITLE
Provide an OAuth example since it will be required starting 1st of May 2020

### ISSUE THREAD

**Issue by Fef0** [nicklaw5/helix#44]
Since Twitch is going to require OAuth Authentication starting from 1st of May 2020 (More [here](https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916)) it would be great to add an Authentication example in order to speed up initial configuration using this API wrapper.

**Comment by nicklaw5** [comment]
This is already supported. See the existing docs and examples: https://github.com/nicklaw5/helix/blob/master/docs/authentication_docs.md.

**Comment by nicklaw5** [comment]
Relates to #42
