### ISSUE TITLE
Oauth Enforced

### ISSUE THREAD

**Issue by blackstar257** [nicklaw5/helix#48]
We should update the library to automatically grab oauth tokens. Just ran into this

Error:Unauthorized ErrorStatus:401 ErrorMessage:OAuth token is missing

**Comment by nicklaw5** [comment]
> We should update the library to automatically grab oauth tokens

That is not an opinion that should be held by a library. A library is for providing core functionality for its intended purpose. Not for enforcing opinions on its users.
