### ISSUE TITLE
Managing response_type

### ISSUE THREAD

**Issue by Scorfly** [nicklaw5/helix#53]
Hi !

The last release broke my project :

https://github.com/nicklaw5/helix/commit/197ab0745aae57735f53fafa06ddd9445838b93e

I use ` url := AuthBaseURL + "/authorize?response_type=code"` because it return an **access_token** and a **refresh_token**

with the `response_type=token`, it doesn't return an **refresh_token**

Did i miss something ?

I think it would be better to pass this as a param of the function

**Comment by nicklaw5** [comment]
Sorry about that. Please pin to the previous release until I can take a closer look.

**Comment by nicklaw5** [comment]
@Scorfly this issue should now be resolved. Please see the latest release: https://github.com/nicklaw5/helix/releases/tag/v0.7.0.

**Comment by Scorfly** [comment]
Thx it's perfect for me ;)
