### ISSUE TITLE
How can I use current access token with ValidateToken?

### ISSUE THREAD

**Issue by lornajane** [nicklaw5/helix#56]
I have an app that runs while I'm streaming, using this library for Twitch integration (thanks!). I'd like to check if the access token is valid before making API calls, since it's quite likely that my token may expire so I can use the refresh token to update it in that case.

How can I get my current access token from the client in order to check if it is valid? Or is there a way to ask the method itself to use the current token rather than a provided one? Is this a feature that would be useful to others?

**Comment by nicklaw5** [comment]
Hi @lornajane. I stalked your GitHub profile and stumbled across your Twitch stream yesterday :smiley: 

After watching you're vod, I can understand what you're wanting to do. You expect `client.GetUserAccessToken()` to return the currently set user access token, right?

As you already know, the `client.GetUserAccessToken()` accepts an authorization code to request an access token from Twitch. In retrospect, naming that method `GetUserAccessToken` is not great given you expect it to return the current access token.

What I propose we do is:
- Rename `GetUserAccessToken` to `RequestUserAccessToken`
- Add two new methods on the client called `GetUserAccessToken` and `GetAppAccessToken` for returning the currently set user and app access tokens, respectively.

That would then allow you to do the following:

```go
isValid, resp, err := client.ValidateToken(client.GetUserAccessToken())
```

Thoughts?

**Comment by lornajane** [comment]
I consider myself stalked :) That sounds great! It sounds like a really breaking change though ... I'd be equally happy with either:
 - `client.GetCurrentUserAccessToken()` as a non-clashing function name
 - `client.ValidateToken()` can just use the access token it has anyway and tell me if it's still going to work now or not

Just tag me if there's a branch I should test or anything, I'm happy to help if I can!

**Comment by nicklaw5** [comment]
@lornajane see #57 

I've introduced the breaking change, which is fine because I intend to bump this project to a v1.0 release.

I have left the `ValidateToken` unchanged as I can see that some people may not want to set the token on the client in order to validate it.

Feel free to test it or offer any suggested changes. Let me know if this resolves your issue.
