### ISSUE TITLE
Support New Twitch API endpoints(2021‑01‑15)

### ISSUE THREAD

**Issue by FlowingSPDG** [nicklaw5/helix#74]
Hi there, thanks for excellent API library!
There are new API endpoints for New Twitch API, `Get Channel Editors`, `Delete Videos`, `Get User Block List`, `Block User`, and`UnblockUser`.
You can see https://dev.twitch.tv/docs/change-log for detail.
Thanks!

**Comment by nicklaw5** [comment]
If you have a minute to spare, do you mind add these the list of endpoints in the [README.md](https://github.com/nicklaw5/helix/blob/master/README.md)?

**Comment by FlowingSPDG** [comment]
yup sure! Also I can add those API codes too :)
I'll make PR once I made one.

**Comment by Scorfly** [comment]
Hi !

 - `Get Channel Editors`
 - `Delete Videos`
 - `Get User Block List`
 - `Block User`
 - `Unblock User`

Those features are now available 😃

**Comment by nicklaw5** [comment]
Thanks @Scorfly
