### ISSUE TITLE
Add missing API endpoints

### ISSUE THREAD

**Issue by nicklaw5** [nicklaw5/helix#8]
The following API endpoints have been added to Twitch's Helix [API docs](https://dev.twitch.tv/docs/api/reference/), but have yet to be implemented in this package:

- ~[Get Extension Analytics](https://dev.twitch.tv/docs/api/reference/#get-extension-analytics)~ (see #9)
- ~[Create Stream Marker](https://dev.twitch.tv/docs/api/reference/#create-stream-marker)~ (see #17)
- ~[Get Stream Markers](https://dev.twitch.tv/docs/api/reference/#get-stream-markers)~ (see #16)
- ~[Get User Extensions](https://dev.twitch.tv/docs/api/reference/#get-user-extensions)~ (see #35)
- ~[Get User Active Extensions](https://dev.twitch.tv/docs/api/reference/#get-user-active-extensions)~ (see #35)
- ~[Update User Extensions](https://dev.twitch.tv/docs/api/reference/#update-user-extensions)~ (see #35)
- ~[Get User Subscriptions](https://dev.twitch.tv/docs/api/reference/#get-user-subscriptions)~ (see #35)
- ~[Get Broadcaster Subscriptions](https://dev.twitch.tv/docs/api/reference/#get-broadcaster-subscriptions)~ (see #28)
- ~[Get Code Status](https://dev.twitch.tv/docs/api/reference/#get-code-status)~ (see #67)
- ~[Redeem Code](https://dev.twitch.tv/docs/api/reference/#redeem-code)~ (see #68)

Any help implementing these endpoints is very much appreciated. All PRs should be accompanied by tests.

**Comment by jackmcguire1** [comment]
Subscription endpoints for felix now released 

https://dev.twitch.tv/docs/api/reference/#get-user-subscriptions
https://dev.twitch.tv/docs/api/reference/#get-broadcaster-subscriptions

**Comment by edalford11** [comment]
The validate request would be really useful as well

https://dev.twitch.tv/docs/authentication#validating-requests

**Comment by intel352** [comment]
@nicklaw5 the list in the OP should be updated. the user subscriptions were in #32 and #35 it appears? Code status was #67 

Someone requested validate request, but it appears that was already addressed in #49?

**Comment by nicklaw5** [comment]
I think we can probably close this off and just go with the list of endpoints that haven't been implemented in the README.md file.

**Comment by nicklaw5** [comment]
Closing this off. Please refer to the list remaining endpoint in the `README.md`.

Thanks to everyone who contributed :+1:
