### ISSUE TITLE
Get Emote Sets missing OwnerID value

### ISSUE THREAD

**Issue by pajlada** [nicklaw5/helix#98]
The [Get Emote Sets](https://github.com/nicklaw5/helix/blob/main/chat.go#L128) function is missing the `OwnerID` value returned [from the API](https://dev.twitch.tv/docs/api/reference#get-emote-sets).

The simple solution is to add `OwnerID` to the `Emote` type, but that'd mean an empty value in the other calls using the type (i.e. Get Channel Emotes and Get Global Emotes).
The complex solution is to return a different type in the response of Get Emote Sets.

I'm happy to make the change with a PR but I'd like to hear your preferred solution first.

**Comment by Scorfly** [comment]
Hello !

I missed this argument when i impleted those calls.

Personally, I would do 2 structs

**Comment by nicklaw5** [comment]
I agree with @Scorfly, let's go with two different structs. A PR would be very much appreciated.
