### ISSUE TITLE
 WebSub webhooks being deprecated

### ISSUE THREAD

**Issue by jackmcguire1** [nicklaw5/helix#99]
Twitch are deprecating their websub-based webhook functionality, in favour of their EventSub API.

- No new twitch applications can utilize webhooks
- Last date of use is September 16, 2021.
- main branch contains  WebSub webhooks code

need to work towards refactoring webhooks.go to support [EventSub](https://dev.twitch.tv/docs/eventsub)

**Comment by Scorfly** [comment]
Event sub are handle in a seperate way

Twitch API has tree endpoints: 
 - Create EventSub Subscription
 - Delete EventSub Subscription
 - Get EventSub Subscriptions

Those endpoints are already impleted and documented :
 - https://github.com/nicklaw5/helix/blob/main/docs/eventsub_docs.md

Is there more needs ?

**Comment by jackmcguire1** [comment]
https://github.com/nicklaw5/helix/pull/107

**Comment by jackmcguire1** [comment]
https://github.com/nicklaw5/helix/pull/112

**Comment by jackmcguire1** [comment]
event subs supported
